export { activitiesHandler } from './activities'
export { newsHandler } from './news'
export { usersHandler } from './users'
export { notificationsHandler } from './notifications'
export { alertsHandler } from './alerts'
